
import com.sun.java.swing.plaf.windows.resources.windows;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Liam
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;

    public AdminPage(LoginPage login, ResultSet rs, Connection conn) {
        login.dispose();
        initComponents();
        setSize(1270, 730);

        setPreferredStates();

        try {
            this.conn = conn;
            st = this.conn.createStatement();
            AdminNameLbl.setText(rs.getString("admin_Name"));
            populateStoresDropdown();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MinLbl = new javax.swing.JLabel();
        ExitLbl = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        StoreNameLbl = new javax.swing.JLabel();
        ContactNumberLbl = new javax.swing.JLabel();
        UsernameLbl = new javax.swing.JLabel();
        StoreAddressLbl = new javax.swing.JLabel();
        StoreNameTf = new javax.swing.JTextField();
        ContactNumberTf = new javax.swing.JTextField();
        UsernameTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        StoreAddressTa = new javax.swing.JTextArea();
        AddStoreBtn = new javax.swing.JButton();
        DeleteStoreBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        DispatchUserLbl = new javax.swing.JLabel();
        DispatchUsernameLbl = new javax.swing.JLabel();
        DispatchPasswordLbl = new javax.swing.JLabel();
        DispatchUsernameTf = new javax.swing.JTextField();
        DispatchPasswordTf = new javax.swing.JTextField();
        DipatchUserDeleteBtn = new javax.swing.JButton();
        DipatchUserAddBtn = new javax.swing.JButton();
        StoreUserLbl = new javax.swing.JLabel();
        AdminUserLbl = new javax.swing.JLabel();
        StoreUsernameLbl = new javax.swing.JLabel();
        StorePasswordLbl = new javax.swing.JLabel();
        StoreIdentityLbl = new javax.swing.JLabel();
        AdminUsernameLbl = new javax.swing.JLabel();
        AdminPasswordLbl = new javax.swing.JLabel();
        StoreUsernameTf = new javax.swing.JTextField();
        StorePasswordTf = new javax.swing.JTextField();
        AdminUsernameTf = new javax.swing.JTextField();
        AdminPasswordTf = new javax.swing.JTextField();
        StoreNameCb = new javax.swing.JComboBox<>();
        StoreUserAddBtn = new javax.swing.JButton();
        StoreUserDeleteBtn = new javax.swing.JButton();
        AdminUserAddBtn = new javax.swing.JButton();
        AdminUserDeleteBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ProductNameLbl = new javax.swing.JLabel();
        UnitsPerCrateLbl = new javax.swing.JLabel();
        ProductNameTf = new javax.swing.JTextField();
        UnitsPerCrateTf = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        lblWarningUnits = new javax.swing.JLabel();
        UnitsPerCrateLbl1 = new javax.swing.JLabel();
        descriptionTf = new javax.swing.JTextField();
        UnitsPerCrateLbl2 = new javax.swing.JLabel();
        CompanyIDTf = new javax.swing.JTextField();
        lblWarningCompanyId = new javax.swing.JLabel();
        lblWarningProduct = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        AdminNameLbl = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        MinLbl.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        MinLbl.setForeground(new java.awt.Color(255, 255, 255));
        MinLbl.setText("-");
        MinLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLblMouseClicked(evt);
            }
        });
        jPanel1.add(MinLbl);
        MinLbl.setBounds(1180, 0, 19, 64);

        ExitLbl.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        ExitLbl.setForeground(new java.awt.Color(255, 255, 255));
        ExitLbl.setText("x");
        ExitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLblMouseClicked(evt);
            }
        });
        jPanel1.add(ExitLbl);
        ExitLbl.setBounds(1220, 0, 27, 64);

        jPanel3.setBackground(new java.awt.Color(133, 1, 41));
        jPanel3.setLayout(null);

        StoreNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StoreNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        StoreNameLbl.setText("Store name:");
        jPanel3.add(StoreNameLbl);
        StoreNameLbl.setBounds(250, 80, 100, 17);

        ContactNumberLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ContactNumberLbl.setForeground(new java.awt.Color(255, 255, 255));
        ContactNumberLbl.setText("Contact number:");
        jPanel3.add(ContactNumberLbl);
        ContactNumberLbl.setBounds(220, 120, 118, 17);

        UsernameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLbl.setText("Username:");
        jPanel3.add(UsernameLbl);
        UsernameLbl.setBounds(260, 160, 80, 17);

        StoreAddressLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StoreAddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        StoreAddressLbl.setText("Store address:");
        jPanel3.add(StoreAddressLbl);
        StoreAddressLbl.setBounds(230, 200, 110, 17);
        jPanel3.add(StoreNameTf);
        StoreNameTf.setBounds(370, 80, 310, 20);
        jPanel3.add(ContactNumberTf);
        ContactNumberTf.setBounds(370, 120, 310, 20);
        jPanel3.add(UsernameTf);
        UsernameTf.setBounds(370, 160, 310, 20);

        StoreAddressTa.setColumns(20);
        StoreAddressTa.setRows(5);
        jScrollPane1.setViewportView(StoreAddressTa);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(370, 200, 310, 180);

        AddStoreBtn.setBackground(new java.awt.Color(168, 153, 104));
        AddStoreBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddStoreBtn.setText("Add");
        AddStoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStoreBtnActionPerformed(evt);
            }
        });
        jPanel3.add(AddStoreBtn);
        AddStoreBtn.setBounds(420, 400, 90, 30);

        DeleteStoreBtn.setBackground(new java.awt.Color(168, 153, 104));
        DeleteStoreBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteStoreBtn.setText("Delete");
        jPanel3.add(DeleteStoreBtn);
        DeleteStoreBtn.setBounds(540, 400, 90, 30);

        jTabbedPane1.addTab("Add/Delete Store", jPanel3);

        jPanel2.setBackground(new java.awt.Color(133, 1, 41));
        jPanel2.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(null);

        DispatchUserLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DispatchUserLbl.setForeground(new java.awt.Color(255, 255, 255));
        DispatchUserLbl.setText("Dispatch User");
        jPanel5.add(DispatchUserLbl);
        DispatchUserLbl.setBounds(90, 50, 170, 40);

        DispatchUsernameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DispatchUsernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        DispatchUsernameLbl.setText("Username:");
        jPanel5.add(DispatchUsernameLbl);
        DispatchUsernameLbl.setBounds(60, 140, 74, 17);

        DispatchPasswordLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DispatchPasswordLbl.setForeground(new java.awt.Color(255, 255, 255));
        DispatchPasswordLbl.setText("Password:");
        jPanel5.add(DispatchPasswordLbl);
        DispatchPasswordLbl.setBounds(60, 190, 90, 30);
        jPanel5.add(DispatchUsernameTf);
        DispatchUsernameTf.setBounds(160, 140, 130, 20);

        DispatchPasswordTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispatchPasswordTfActionPerformed(evt);
            }
        });
        jPanel5.add(DispatchPasswordTf);
        DispatchPasswordTf.setBounds(160, 200, 130, 20);

        DipatchUserDeleteBtn.setBackground(new java.awt.Color(168, 153, 104));
        DipatchUserDeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DipatchUserDeleteBtn.setText("Delete User");
        jPanel5.add(DipatchUserDeleteBtn);
        DipatchUserDeleteBtn.setBounds(190, 340, 110, 23);

        DipatchUserAddBtn.setBackground(new java.awt.Color(168, 153, 104));
        DipatchUserAddBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DipatchUserAddBtn.setText("Add User");
        jPanel5.add(DipatchUserAddBtn);
        DipatchUserAddBtn.setBounds(40, 340, 110, 23);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(350, 0, 340, 460);

        StoreUserLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        StoreUserLbl.setForeground(new java.awt.Color(255, 255, 255));
        StoreUserLbl.setText("Store User");
        jPanel2.add(StoreUserLbl);
        StoreUserLbl.setBounds(110, 50, 130, 30);

        AdminUserLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminUserLbl.setForeground(new java.awt.Color(255, 255, 255));
        AdminUserLbl.setText("Admin User");
        jPanel2.add(AdminUserLbl);
        AdminUserLbl.setBounds(800, 50, 150, 40);

        StoreUsernameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StoreUsernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        StoreUsernameLbl.setText("Username:");
        jPanel2.add(StoreUsernameLbl);
        StoreUsernameLbl.setBounds(70, 140, 90, 20);

        StorePasswordLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StorePasswordLbl.setForeground(new java.awt.Color(255, 255, 255));
        StorePasswordLbl.setText("Password:");
        jPanel2.add(StorePasswordLbl);
        StorePasswordLbl.setBounds(70, 200, 80, 20);

        StoreIdentityLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StoreIdentityLbl.setForeground(new java.awt.Color(255, 255, 255));
        StoreIdentityLbl.setText("Store:");
        jPanel2.add(StoreIdentityLbl);
        StoreIdentityLbl.setBounds(100, 260, 60, 17);

        AdminUsernameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminUsernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        AdminUsernameLbl.setText("Username:");
        jPanel2.add(AdminUsernameLbl);
        AdminUsernameLbl.setBounds(750, 140, 80, 30);

        AdminPasswordLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminPasswordLbl.setForeground(new java.awt.Color(255, 255, 255));
        AdminPasswordLbl.setText("Password:");
        jPanel2.add(AdminPasswordLbl);
        AdminPasswordLbl.setBounds(750, 200, 80, 20);
        jPanel2.add(StoreUsernameTf);
        StoreUsernameTf.setBounds(170, 140, 130, 20);
        jPanel2.add(StorePasswordTf);
        StorePasswordTf.setBounds(170, 200, 130, 20);
        jPanel2.add(AdminUsernameTf);
        AdminUsernameTf.setBounds(850, 150, 130, 20);
        jPanel2.add(AdminPasswordTf);
        AdminPasswordTf.setBounds(850, 200, 130, 20);

        jPanel2.add(StoreNameCb);
        StoreNameCb.setBounds(170, 260, 130, 20);

        StoreUserAddBtn.setBackground(new java.awt.Color(168, 153, 104));
        StoreUserAddBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StoreUserAddBtn.setText("Add User");
        jPanel2.add(StoreUserAddBtn);
        StoreUserAddBtn.setBounds(50, 340, 110, 25);

        StoreUserDeleteBtn.setBackground(new java.awt.Color(168, 153, 104));
        StoreUserDeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StoreUserDeleteBtn.setText("Delete User");
        jPanel2.add(StoreUserDeleteBtn);
        StoreUserDeleteBtn.setBounds(190, 340, 110, 25);

        AdminUserAddBtn.setBackground(new java.awt.Color(168, 153, 104));
        AdminUserAddBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminUserAddBtn.setText("Add User");
        jPanel2.add(AdminUserAddBtn);
        AdminUserAddBtn.setBounds(740, 340, 110, 25);

        AdminUserDeleteBtn.setBackground(new java.awt.Color(168, 153, 104));
        AdminUserDeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminUserDeleteBtn.setText("Delete User");
        jPanel2.add(AdminUserDeleteBtn);
        AdminUserDeleteBtn.setBounds(880, 340, 110, 25);

        jTabbedPane1.addTab("Add/Delete User", jPanel2);

        jPanel4.setBackground(new java.awt.Color(133, 1, 41));
        jPanel4.setLayout(null);

        ProductNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProductNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        ProductNameLbl.setText("Product name:");
        jPanel4.add(ProductNameLbl);
        ProductNameLbl.setBounds(350, 150, 110, 30);

        UnitsPerCrateLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UnitsPerCrateLbl.setForeground(new java.awt.Color(255, 255, 255));
        UnitsPerCrateLbl.setText("Description");
        jPanel4.add(UnitsPerCrateLbl);
        UnitsPerCrateLbl.setBounds(350, 200, 120, 30);
        jPanel4.add(ProductNameTf);
        ProductNameTf.setBounds(480, 150, 220, 30);
        jPanel4.add(UnitsPerCrateTf);
        UnitsPerCrateTf.setBounds(480, 250, 220, 30);

        AddBtn.setBackground(new java.awt.Color(168, 153, 104));
        AddBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        jPanel4.add(AddBtn);
        AddBtn.setBounds(400, 350, 100, 30);

        DeleteBtn.setBackground(new java.awt.Color(168, 153, 104));
        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteBtn.setText("Delete");
        jPanel4.add(DeleteBtn);
        DeleteBtn.setBounds(550, 350, 100, 30);

        lblWarningUnits.setBackground(new java.awt.Color(255, 153, 51));
        lblWarningUnits.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningUnits.setText("warning");
        jPanel4.add(lblWarningUnits);
        lblWarningUnits.setBounds(710, 260, 210, 14);

        UnitsPerCrateLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UnitsPerCrateLbl1.setForeground(new java.awt.Color(255, 255, 255));
        UnitsPerCrateLbl1.setText("Units per crate:");
        jPanel4.add(UnitsPerCrateLbl1);
        UnitsPerCrateLbl1.setBounds(350, 250, 120, 30);
        jPanel4.add(descriptionTf);
        descriptionTf.setBounds(480, 200, 220, 30);

        UnitsPerCrateLbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UnitsPerCrateLbl2.setForeground(new java.awt.Color(255, 255, 255));
        UnitsPerCrateLbl2.setText("Company ID");
        jPanel4.add(UnitsPerCrateLbl2);
        UnitsPerCrateLbl2.setBounds(350, 300, 120, 30);
        jPanel4.add(CompanyIDTf);
        CompanyIDTf.setBounds(480, 300, 220, 30);

        lblWarningCompanyId.setBackground(new java.awt.Color(255, 153, 51));
        lblWarningCompanyId.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningCompanyId.setText("warning");
        jPanel4.add(lblWarningCompanyId);
        lblWarningCompanyId.setBounds(710, 310, 210, 14);

        lblWarningProduct.setBackground(new java.awt.Color(255, 153, 51));
        lblWarningProduct.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningProduct.setText("warning");
        jPanel4.add(lblWarningProduct);
        lblWarningProduct.setBounds(710, 160, 210, 14);

        jTabbedPane1.addTab("Add/Delete Product", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(120, 130, 1040, 490);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(null);

        AdminNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        AdminNameLbl.setText("AdminName");
        jPanel6.add(AdminNameLbl);
        AdminNameLbl.setBounds(760, 0, 240, 70);

        btnSignOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSignOut.setText("Sign Out");
        btnSignOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(133, 1, 41), 3, true));
        btnSignOut.setContentAreaFilled(false);
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        jPanel6.add(btnSignOut);
        btnSignOut.setBounds(940, 20, 90, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(120, 90, 1040, 530);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Lifestyle_Overlay.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1270, 740);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1270, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLblMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinLblMouseClicked

    private void ExitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitLblMouseClicked

    private void DispatchPasswordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispatchPasswordTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DispatchPasswordTfActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        LoginPage lp = new LoginPage();
        lp.signOut(this);
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void AddStoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStoreBtnActionPerformed
        addStore(StoreNameTf.getText(), ContactNumberTf.getText(), UsernameTf.getText(), StoreAddressTa.getText());
    }//GEN-LAST:event_AddStoreBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        addProduct(ProductNameTf.getText(), descriptionTf.getText(), UnitsPerCrateTf.getText(), CompanyIDTf.getText());
    }//GEN-LAST:event_AddBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton AddStoreBtn;
    private javax.swing.JLabel AdminNameLbl;
    private javax.swing.JLabel AdminPasswordLbl;
    private javax.swing.JTextField AdminPasswordTf;
    private javax.swing.JButton AdminUserAddBtn;
    private javax.swing.JButton AdminUserDeleteBtn;
    private javax.swing.JLabel AdminUserLbl;
    private javax.swing.JLabel AdminUsernameLbl;
    private javax.swing.JTextField AdminUsernameTf;
    private javax.swing.JTextField CompanyIDTf;
    private javax.swing.JLabel ContactNumberLbl;
    private javax.swing.JTextField ContactNumberTf;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DeleteStoreBtn;
    private javax.swing.JButton DipatchUserAddBtn;
    private javax.swing.JButton DipatchUserDeleteBtn;
    private javax.swing.JLabel DispatchPasswordLbl;
    private javax.swing.JTextField DispatchPasswordTf;
    private javax.swing.JLabel DispatchUserLbl;
    private javax.swing.JLabel DispatchUsernameLbl;
    private javax.swing.JTextField DispatchUsernameTf;
    private javax.swing.JLabel ExitLbl;
    private javax.swing.JLabel MinLbl;
    private javax.swing.JLabel ProductNameLbl;
    private javax.swing.JTextField ProductNameTf;
    private javax.swing.JLabel StoreAddressLbl;
    private javax.swing.JTextArea StoreAddressTa;
    private javax.swing.JLabel StoreIdentityLbl;
    private javax.swing.JComboBox<String> StoreNameCb;
    private javax.swing.JLabel StoreNameLbl;
    private javax.swing.JTextField StoreNameTf;
    private javax.swing.JLabel StorePasswordLbl;
    private javax.swing.JTextField StorePasswordTf;
    private javax.swing.JButton StoreUserAddBtn;
    private javax.swing.JButton StoreUserDeleteBtn;
    private javax.swing.JLabel StoreUserLbl;
    private javax.swing.JLabel StoreUsernameLbl;
    private javax.swing.JTextField StoreUsernameTf;
    private javax.swing.JLabel UnitsPerCrateLbl;
    private javax.swing.JLabel UnitsPerCrateLbl1;
    private javax.swing.JLabel UnitsPerCrateLbl2;
    private javax.swing.JTextField UnitsPerCrateTf;
    private javax.swing.JLabel UsernameLbl;
    private javax.swing.JTextField UsernameTf;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JTextField descriptionTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblWarningCompanyId;
    private javax.swing.JLabel lblWarningProduct;
    private javax.swing.JLabel lblWarningUnits;
    // End of variables declaration//GEN-END:variables

    private void addStore(String store, String phone, String username, String address) {

    }

    private void populateStoresDropdown() throws SQLException {

        rs = st.executeQuery("SELECT * FROM store");
        while (rs.next()) {
            StoreNameCb.addItem(rs.getInt("store_ID") + ":" + rs.getString("store_Name"));
        }

    }

    private void addProduct(String name, String description, String units, String compID) {

        boolean valid = true;
        int amount = -1;
        try {
            amount = Integer.parseInt(units);
            lblWarningUnits.setVisible(false);
        } catch (NumberFormatException e) {
            valid = false;
            lblWarningUnits.setText("Invalid input");
            UnitsPerCrateTf.setText("");
            lblWarningUnits.setVisible(true);
        }
        int c_ID = -1;
        try {
            c_ID = Integer.parseInt(compID);
        } catch (NumberFormatException e) {
            valid = false;
            lblWarningCompanyId.setText("Invalid input");
            CompanyIDTf.setText("");
            lblWarningCompanyId.setVisible(true);
        }
        try {
            if (companyExists(c_ID) & !productExists(name) & valid) {
                st.executeUpdate("INSERT INTO product (product_Name, product_Description, company_ID) VALUES ('','',)");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void setPreferredStates() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        lblWarningUnits.setVisible(false);
        lblWarningCompanyId.setVisible(false);
        lblWarningProduct.setVisible(false);
    }

    private boolean companyExists(int c_ID) throws SQLException {
        rs = st.executeQuery("SELECT * FROM company WHERE company_ID= " + c_ID + ";");
        System.out.println("asd");
        if (rs.next()) {
            System.out.println("Exists company");
            lblWarningCompanyId.setVisible(false);
            return true;
        } else {
            lblWarningCompanyId.setVisible(true);
            lblWarningCompanyId.setText("Invalid company ID.");
            return false;
        }
    }

    private boolean productExists(String name) throws SQLException {

        rs = st.executeQuery("SELECT * FROM PRODUCT WHERE product_Name = '" + name + "';");
        if (rs.next()) {
            System.out.println("Exists");
            lblWarningProduct.setVisible(true);
            lblWarningProduct.setText("Product already exists.");
            return true;
        } else {
            lblWarningProduct.setVisible(false);
            return false;
        }
    }

}
