
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Liam
 */
public class DispatchPage extends javax.swing.JFrame {

    /**
     * Creates new form DispatchPage
     */
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;
    ArrayList<Object[]> orderList = new ArrayList();

    public DispatchPage(LoginPage login, ResultSet rs, Connection conn) {
        login.dispose();
        initComponents();
        setSize(1270, 730);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        displayProducts();
        
        try {
            this.conn = conn;
            displayOrders();
        } catch (SQLException ex) {
            Logger.getLogger(DispatchPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        IncomingOrdersTbl.setRowSelectionInterval(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ExitLbl = new javax.swing.JLabel();
        MinLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        OrdersLbl = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        PreviousBtn = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();
        FirstBtn = new javax.swing.JButton();
        LastBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        IncomingOrdersTbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        SelectedOrderTbl = new javax.swing.JTable();
        ProcessOrderBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        ExitLbl.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        ExitLbl.setForeground(new java.awt.Color(255, 255, 255));
        ExitLbl.setText("x");
        ExitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLblMouseClicked(evt);
            }
        });
        jPanel1.add(ExitLbl);
        ExitLbl.setBounds(1220, 0, 27, 64);

        MinLbl.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        MinLbl.setForeground(new java.awt.Color(255, 255, 255));
        MinLbl.setText("-");
        MinLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLblMouseClicked(evt);
            }
        });
        jPanel1.add(MinLbl);
        MinLbl.setBounds(1180, 0, 19, 64);

        jPanel2.setBackground(new java.awt.Color(133, 1, 41));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        OrdersLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        OrdersLbl.setForeground(new java.awt.Color(255, 255, 255));
        OrdersLbl.setText("Orders");
        jPanel3.add(OrdersLbl);
        OrdersLbl.setBounds(50, 14, 140, 30);

        btnSignOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSignOut.setText("Sign Out");
        btnSignOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(133, 1, 41), 3, true));
        btnSignOut.setContentAreaFilled(false);
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        jPanel3.add(btnSignOut);
        btnSignOut.setBounds(990, 10, 90, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1100, 60);

        PreviousBtn.setBackground(new java.awt.Color(168, 153, 104));
        PreviousBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PreviousBtn.setText("Previous");
        PreviousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousBtnActionPerformed(evt);
            }
        });
        jPanel2.add(PreviousBtn);
        PreviousBtn.setBounds(180, 90, 100, 25);

        NextBtn.setBackground(new java.awt.Color(168, 153, 104));
        NextBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NextBtn.setText("Next");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });
        jPanel2.add(NextBtn);
        NextBtn.setBounds(310, 90, 100, 25);

        FirstBtn.setBackground(new java.awt.Color(168, 153, 104));
        FirstBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstBtn.setText("First");
        FirstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstBtnActionPerformed(evt);
            }
        });
        jPanel2.add(FirstBtn);
        FirstBtn.setBounds(180, 130, 100, 25);

        LastBtn.setBackground(new java.awt.Color(168, 153, 104));
        LastBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastBtn.setText("Last");
        LastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LastBtn);
        LastBtn.setBounds(310, 130, 100, 25);

        IncomingOrdersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        IncomingOrdersTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IncomingOrdersTblMouseClicked(evt);
            }
        });
        IncomingOrdersTbl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                IncomingOrdersTblPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(IncomingOrdersTbl);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(80, 180, 440, 280);

        SelectedOrderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(SelectedOrderTbl);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(582, 92, 440, 370);

        ProcessOrderBtn.setBackground(new java.awt.Color(168, 153, 104));
        ProcessOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProcessOrderBtn.setText("Process Order");
        jPanel2.add(ProcessOrderBtn);
        ProcessOrderBtn.setBounds(230, 480, 130, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 100, 1090, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Lifestyle_Overlay.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1270, 730);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1270, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitLblMouseClicked

    private void MinLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLblMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinLblMouseClicked

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        LoginPage lp = new LoginPage();
        lp.signOut(this);
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void IncomingOrdersTblPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_IncomingOrdersTblPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_IncomingOrdersTblPropertyChange

    private void IncomingOrdersTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomingOrdersTblMouseClicked
        System.out.println(IncomingOrdersTbl.getSelectedRow());
        System.out.println(IncomingOrdersTbl.getAccessibleContext());
    }//GEN-LAST:event_IncomingOrdersTblMouseClicked

    private void PreviousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousBtnActionPerformed
        if (IncomingOrdersTbl.getSelectedRow() != 0) {
            int prevRow = IncomingOrdersTbl.getSelectedRow() - 1;
            IncomingOrdersTbl.setRowSelectionInterval(prevRow, prevRow);
        } else {
            IncomingOrdersTbl.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_PreviousBtnActionPerformed

    private void FirstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstBtnActionPerformed
        IncomingOrdersTbl.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_FirstBtnActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        int lastRow = IncomingOrdersTbl.getRowCount();
        if (IncomingOrdersTbl.getSelectedRow() != lastRow) {
            int nextRow = IncomingOrdersTbl.getSelectedRow() + 1;
            IncomingOrdersTbl.setRowSelectionInterval(nextRow, nextRow);
        } else {
            IncomingOrdersTbl.setRowSelectionInterval(lastRow-1, lastRow-1);
        }
    }//GEN-LAST:event_NextBtnActionPerformed

    private void LastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastBtnActionPerformed
        int lastRow = IncomingOrdersTbl.getRowCount();
        IncomingOrdersTbl.setRowSelectionInterval(lastRow-1, lastRow-1);
    }//GEN-LAST:event_LastBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitLbl;
    private javax.swing.JButton FirstBtn;
    private javax.swing.JTable IncomingOrdersTbl;
    private javax.swing.JButton LastBtn;
    private javax.swing.JLabel MinLbl;
    private javax.swing.JButton NextBtn;
    private javax.swing.JLabel OrdersLbl;
    private javax.swing.JButton PreviousBtn;
    private javax.swing.JButton ProcessOrderBtn;
    private javax.swing.JTable SelectedOrderTbl;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void displayProducts() {
//        Resul
    }

    private void displayOrders() throws SQLException {
        st = conn.createStatement();
        rs = st.executeQuery("SELECT * FROM Orders ORDER BY order_Status, order_Date");
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Order ID", "Order Date", "Store", "Order Status"}, 0);

        while (rs.next()) {
            //System.out.println(a++);
            //System.out.println(rs.getInt("order_ID") + "," + rs.getInt("order_Status"));

            if (rs.getInt("order_Status") > 0) {
                Object order[] = {rs.getInt("order_ID"), rs.getDate("order_Date"), getStoreName(rs.getInt("store_ID")), "Complete"};
                orderList.add(order);
            } else {
                Object order[] = {rs.getInt("order_ID"), rs.getDate("order_Date"), getStoreName(rs.getInt("store_ID")), "Incomplete"};
                orderList.add(order);
            }
            //System.out.println(orderList.size());
            model.addRow(orderList.get(orderList.size() - 1));
        }
        IncomingOrdersTbl.setModel(model);
    }

    private String getStoreName(int ID) {
        String store_Name = null;
        Statement st_1; 
        ResultSet rs_1;

        try {
            st_1 = conn.createStatement();
            rs_1 = st_1.executeQuery("SELECT store_Name FROM Store WHERE store_ID =" + ID);
            while (rs_1.next()) {
                store_Name = rs_1.getString("store_Name");
            }

        } catch (SQLException e) {
            Logger.getLogger(DispatchPage.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("Here");
        }
        return store_Name;
    }

}
