
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Liam
 */
public class DispatchPage extends javax.swing.JFrame {

    /**
     * Creates new form DispatchPage
     */
    public DispatchPage() {
        initComponents();
        setSize(1270,730);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ExitLbl = new javax.swing.JLabel();
        MinLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        OrdersLbl = new javax.swing.JLabel();
        PreviousBtn = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();
        FirstBtn = new javax.swing.JButton();
        LastBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        IncomingOrdersTbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        SelectedOrderTbl = new javax.swing.JTable();
        ProcessOrderBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        StoreLbl = new javax.swing.JLabel();
        DateLbl = new javax.swing.JLabel();
        StoreTf = new javax.swing.JTextField();
        DateTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        ExitLbl.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        ExitLbl.setForeground(new java.awt.Color(255, 255, 255));
        ExitLbl.setText("x");
        ExitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLblMouseClicked(evt);
            }
        });
        jPanel1.add(ExitLbl);
        ExitLbl.setBounds(1220, 0, 27, 64);

        MinLbl.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        MinLbl.setForeground(new java.awt.Color(255, 255, 255));
        MinLbl.setText("-");
        MinLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLblMouseClicked(evt);
            }
        });
        jPanel1.add(MinLbl);
        MinLbl.setBounds(1180, 0, 19, 64);

        jPanel2.setBackground(new java.awt.Color(133, 1, 41));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        OrdersLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        OrdersLbl.setForeground(new java.awt.Color(255, 255, 255));
        OrdersLbl.setText("Orders");
        jPanel3.add(OrdersLbl);
        OrdersLbl.setBounds(50, 14, 140, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1100, 60);

        PreviousBtn.setBackground(new java.awt.Color(168, 153, 104));
        PreviousBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PreviousBtn.setText("Previous");
        jPanel2.add(PreviousBtn);
        PreviousBtn.setBounds(180, 90, 100, 25);

        NextBtn.setBackground(new java.awt.Color(168, 153, 104));
        NextBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NextBtn.setText("Next");
        jPanel2.add(NextBtn);
        NextBtn.setBounds(310, 90, 100, 25);

        FirstBtn.setBackground(new java.awt.Color(168, 153, 104));
        FirstBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstBtn.setText("First");
        jPanel2.add(FirstBtn);
        FirstBtn.setBounds(180, 130, 100, 25);

        LastBtn.setBackground(new java.awt.Color(168, 153, 104));
        LastBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastBtn.setText("Last");
        jPanel2.add(LastBtn);
        LastBtn.setBounds(310, 130, 100, 25);

        IncomingOrdersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(IncomingOrdersTbl);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(80, 180, 440, 280);

        SelectedOrderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(SelectedOrderTbl);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(582, 182, 440, 280);

        ProcessOrderBtn.setBackground(new java.awt.Color(168, 153, 104));
        ProcessOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProcessOrderBtn.setText("Process Order");
        jPanel2.add(ProcessOrderBtn);
        ProcessOrderBtn.setBounds(150, 480, 130, 25);

        LogOutBtn.setBackground(new java.awt.Color(168, 153, 104));
        LogOutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogOutBtn.setText("Log Out");
        jPanel2.add(LogOutBtn);
        LogOutBtn.setBounds(310, 480, 130, 25);

        StoreLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StoreLbl.setForeground(new java.awt.Color(255, 255, 255));
        StoreLbl.setText("Store:");
        jPanel2.add(StoreLbl);
        StoreLbl.setBounds(650, 90, 50, 17);

        DateLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateLbl.setForeground(new java.awt.Color(255, 255, 255));
        DateLbl.setText("Date:");
        jPanel2.add(DateLbl);
        DateLbl.setBounds(650, 130, 50, 17);
        jPanel2.add(StoreTf);
        StoreTf.setBounds(710, 90, 260, 20);
        jPanel2.add(DateTf);
        DateTf.setBounds(710, 130, 260, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 100, 1090, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Lifestyle_Overlay.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1270, 730);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1270, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitLblMouseClicked

    private void MinLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLblMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DispatchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DispatchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DispatchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DispatchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DispatchPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateLbl;
    private javax.swing.JTextField DateTf;
    private javax.swing.JLabel ExitLbl;
    private javax.swing.JButton FirstBtn;
    private javax.swing.JTable IncomingOrdersTbl;
    private javax.swing.JButton LastBtn;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JLabel MinLbl;
    private javax.swing.JButton NextBtn;
    private javax.swing.JLabel OrdersLbl;
    private javax.swing.JButton PreviousBtn;
    private javax.swing.JButton ProcessOrderBtn;
    private javax.swing.JTable SelectedOrderTbl;
    private javax.swing.JLabel StoreLbl;
    private javax.swing.JTextField StoreTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
