
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Liam
 */
public class LoginPage extends javax.swing.JFrame {

    String DB_URL = "";
    String DB_Username;
    String DB_Password;
    Connection conn = null;

    Statement st = null;

    ResultSet rs = null;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setSize(1270, 730);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        UsernameTf = new javax.swing.JTextField();
        PasswordTf = new javax.swing.JTextField();
        UsernameLbl = new javax.swing.JLabel();
        PasswordLbl = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        ExitLbl = new javax.swing.JLabel();
        MinLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(133, 1, 41));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Capture2.PNG"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 0, 260, 394);
        jPanel1.add(UsernameTf);
        UsernameTf.setBounds(100, 130, 140, 30);
        jPanel1.add(PasswordTf);
        PasswordTf.setBounds(100, 180, 140, 30);

        UsernameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLbl.setText("Username:");
        jPanel1.add(UsernameLbl);
        UsernameLbl.setBounds(20, 130, 80, 30);

        PasswordLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordLbl.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLbl.setText("Password:");
        jPanel1.add(PasswordLbl);
        PasswordLbl.setBounds(20, 180, 80, 30);

        buttonLogin.setBackground(new java.awt.Color(168, 153, 104));
        buttonLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogin);
        buttonLogin.setBounds(70, 230, 120, 30);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(380, 170, 510, 390);

        ExitLbl.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        ExitLbl.setForeground(new java.awt.Color(255, 255, 255));
        ExitLbl.setText("x");
        ExitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLblMouseClicked(evt);
            }
        });
        jPanel2.add(ExitLbl);
        ExitLbl.setBounds(1220, 0, 27, 64);

        MinLbl.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        MinLbl.setForeground(new java.awt.Color(255, 255, 255));
        MinLbl.setText("-");
        MinLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLblMouseClicked(evt);
            }
        });
        jPanel2.add(MinLbl);
        MinLbl.setBounds(1180, 0, 19, 64);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Lifestyle_Overlay.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1270, 730);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1270, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitLblMouseClicked

    private void MinLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLblMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinLblMouseClicked

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        login(UsernameTf.getText(), PasswordTf.getText());

    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitLbl;
    private javax.swing.JLabel MinLbl;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JTextField PasswordTf;
    private javax.swing.JLabel UsernameLbl;
    private javax.swing.JTextField UsernameTf;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void login(String text, String password) {
        while (conn == null) {
            conn = getConnection();
        }
        st = createStatement();
        if (isAdminLogin(text, password)) {

        } else if (isStoreLogin()) {

        } else if (isDispatchLogin()) {

        }

    }

    private boolean isLogin(String roleTableName, String username, String password) {
        
        String query = "SELECT * FROM "+ roleTableName +" WHERE username = '" + username + "' AND password = '" + password + "';";
        try {
            rs = st.executeQuery(query);
            while(rs.next()){
                login = new login();
                login.id = rs.getInt("user_id");
                login.name = rs.getInt("user_id");
            }
            return true;
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Connection getConnection() {
        if (DB_URL.isEmpty()) {
            DB_URL = enterDB_URL();
        }
        if (DB_Username.isEmpty()) {
            DB_Username = enterDB_Username();
        }
        if (DB_Password.isEmpty()) {
            DB_Password = enterDB_Password();
        }
        try {
            return DriverManager.getConnection(DB_URL, DB_Password, DB_Password);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Incorrect URL or login for database. /n Please enter valid details.");
            return null;
        }
    }

    private String enterDB_URL() {
        DB_URL = JOptionPane.showInputDialog(null, "Database URL:");
        while (DB_URL == null || DB_URL.isEmpty()) {
            DB_URL = JOptionPane.showInputDialog(null, "Database URL:");
        }
        return DB_URL;
    }

    private String enterDB_Username() {
        DB_Username = JOptionPane.showInputDialog(null, "Database Username:");
        while (DB_Username == null || DB_Username.isEmpty()) {
            DB_Username = JOptionPane.showInputDialog(null, "Database Username:");
        }
        return DB_Username;
    }

    private String enterDB_Password() {
        DB_Password = JOptionPane.showInputDialog(null, "Database Password:");
        while (DB_Password == null || DB_Password.isEmpty()) {
            DB_Password = JOptionPane.showInputDialog(null, "Database Password:");
        }
        return DB_Password;
    }

    private Statement createStatement() {
        conn.createStatement(); //To change body of generated methods, choose Tools | Templates.
    }
}
